FROM ubuntu:22.04

# Install necessary tools
RUN apt-get update && apt-get install -y \
    openssh-server \
    openssh-client \
    iputils-ping \
    net-tools \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Setup SSH
RUN mkdir -p /run/sshd
RUN mkdir -p /root/.ssh
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "root:client" | chpasswd

CMD ["/usr/sbin/sshd", "-D"]
